POST http://localhost:3000/api/user HTTP/1.1
Content-Type: application/json


{
  "firstName":"Dohn",
  "lastName":"Gnow",
  "email": "JohnSno11@gmail.com",
  "password": "dfsdg34",
  "birthday": "1965-02-04",
  "isMale": true
}